---
title: "Nova variavel"
output: html_notebook
---



```{r}
# Carregando pacotes necessários. 

library(srvyr)
library("dplyr")
library("readxl")
library(survival)
library(survey)
library(flexsurv)
library(devtools)

# Lendo os dados da pensi 2015. 
BaseBR2015 = read.csv2(file = 'arquivos csv/PENSE_AMOSTRA1_ALUNOESCOLA.csv',header=T,sep=";")

```

# Criando a nova variavel.
```{r}
i = 1 

#0 censura a direita, 1 falha

tempo = c()
censura = c()

while (i <= length(BaseBR2015$VB08002)){
  
  if (BaseBR2015$VB08002[i] == -1){
    
    tempo = append(tempo,BaseBR2015$VB01003[i])
    censura = append(censura, 0)
    i = i + 1
  }  
  
  
  else if (BaseBR2015$VB08002[i]>=9 && BaseBR2015$VB08002[i]<=18){
    
    tempo = append(tempo,BaseBR2015$VB08002[i])
    censura = append(censura, 1)
    i = i + 1
  }
    
  
  else if (BaseBR2015$VB08002[i] == 99 || BaseBR2015$VB08001[i] == 99){
    tempo = append(tempo, "N.A")
    censura = append(censura, "N.A")
    i = i + 1
    
  }
}


```

# Adicionando as variaveis no data frame 

```{r}
# A coluna tempo diz respeito ao tempo até a primeira relação sexual, seguido da coluna censura a direita ao lado. 
BaseBR2015["Tempo"] = tempo 
BaseBR2015["Censura"] = censura

```

#Aplicando o desenho da amostra
```{r}
desenho = svydesign(id =~ escola,
                    
  strata =~ ESTRATOGEOREG,
  weights =~ as.numeric(PESO),
  data = BaseBR2015,
  nest = T)



```