---
title: "R Notebook"
output: html_notebook
---

 

```{r}
################################
# Carregando pacotes necessários.
################################
library(srvyr)
library("dplyr")
library("readxl")
library(survival)
library(survey)
library(flexsurv)
library(devtools)


BaseBR2015 = read.csv2(file = 'PENSE.csv',header=T, sep=";")
attach(BaseBR2015)

i = 1 
tempo = c()
censura = c()
while (i <= length(BaseBR2015$VB08002)){
  
  if (BaseBR2015$VB08002[i] == -1){
    
    tempo = append(tempo,BaseBR2015$VB01003[i])
    censura = append(censura, 0)
    i = i + 1
  }  
  
  
  else if (BaseBR2015$VB08002[i]>=9 && BaseBR2015$VB08002[i]<=18){
    
    tempo = append(tempo,BaseBR2015$VB08002[i])
    censura = append(censura, 1)
    i = i + 1
  }
    
  
  else if (BaseBR2015$VB08002[i] == 99 || BaseBR2015$VB08001[i] == 99){
    tempo = append(tempo, NA)
    censura = append(censura, NA) # o ERRO ESTÃ NO NA COMO STRING
    i = i + 1
    
  }
}
  
BaseBR2015 <- transform(BaseBR2015, tempo=tempo, censura=censura)
names(BaseBR2015)

desenho = svydesign(id =~ escola,
                    
  strata =~ ESTRATOGEOREG,
  weights =~ as.numeric(PESO),
  data = BaseBR2015,
  nest = T)
desenho_RJ = subset(desenho, UFCENSO == 33 & TIPO_MUNIC == 1) 
```


```{r}
ekm = svykm(Surv(tempo,censura)~1,design = desenho_RJ )
b = plot(ekm,  xlab="Tempo (anos)",xlim = c(7,19), ylab="S(t) estimada")
Legenda = c("Kaplan-Meier ")
legend("bottomleft", Legenda)
```

### Estimação dos parametros e intervalo de confiança do paramêtro
```{r}
ajuste_logn= svysurvreg(Surv(tempo,censura)~1,design = desenho_RJ, dist='lognorm')
ajuste_logn

print("------------------------------------------------------------------------")

mu_logn<-ajuste_logn$coefficients[1]
sigma_logn<-ajuste_logn$scale
cbind(mu_logn,sigma_logn)

print("------------------------------------------------------------------------")

var_mu<-ajuste_logn$var[1,1]
var_mu

print("------------------------------------------------------------------------")

IC_mu<-c(mu_logn-qnorm(0.975)*sqrt(var_mu),mu_logn+qnorm(0.975)*sqrt(var_mu))
IC_mu


print("------------------------------------------------------------------------")

var_sigma<-ajuste_logn$var[2,2]
var_sigma

print("------------------------------------------------------------------------")

IC_sigma<-c(sigma_logn-qnorm(0.975)*sqrt(var_sigma),sigma_logn+qnorm(0.975)*sqrt(var_sigma))
IC_sigma

```
### Estimação do tempo médio da iniciação sexual pela lognormal
```{r}
E_T=exp(mu_logn+(sigma_logn^2)/2)
E_T

```

### Estimação do percentil 100p%:
```{r}
perc_logn<-function(p){exp(qnorm(p)*sigma_logn+mu_logn)}
perc_logn(p=0.80)

plot(perc_logn,ylab="tp (em anos)",xlab="p")
```

### Estimação da função de sobrevivência:

```{r}
S_logn<-function(t){pnorm((-log(t)+mu_logn)/sigma_logn)}
S_logn(t=19.01)

plot(S_logn,ylab="S(t)",xlab="t (em anos)",xlim=c(0,40))
```

### Estimação da função de taxa de falha:
```{r}
f_logn<-function(t){(1/(sqrt(2*pi)*t*sigma_logn))*exp(-0.5*((log(t)-mu_logn)/sigma_logn)^2)}
lambda_logn<-function(t){f_logn(t)/S_logn(t)}

plot(lambda_logn,ylab=expression(lambda(t)),xlab="t (em meses)",xlim=c(0,45))'
```


```{r}
```

```{r}
```
