---
title: "R Notebook"
output: html_notebook
---


```{r}

################################
# Carregando pacotes necessários.
################################
library(srvyr)
library("dplyr")
library("readxl")
library(survival)
library(survey)
library(flexsurv)
library(devtools)


BaseBR2015 = read.csv2(file = 'PENSE.csv',header=T, sep=";")
attach(BaseBR2015)

i = 1 
tempo = c()
censura = c()
while (i <= length(BaseBR2015$VB08002)){
  
  if (BaseBR2015$VB08002[i] == -1){
    
    tempo = append(tempo,BaseBR2015$VB01003[i])
    censura = append(censura, 0)
    i = i + 1
  }  
  
  
  else if (BaseBR2015$VB08002[i]>=9 && BaseBR2015$VB08002[i]<=18){
    
    tempo = append(tempo,BaseBR2015$VB08002[i])
    censura = append(censura, 1)
    i = i + 1
  }
    
  
  else if (BaseBR2015$VB08002[i] == 99 || BaseBR2015$VB08001[i] == 99){
    tempo = append(tempo, NA)
    censura = append(censura, NA) # o ERRO ESTÃ NO NA COMO STRING
    i = i + 1
    
  }
}
  
BaseBR2015 <- transform(BaseBR2015, tempo=tempo, censura=censura)
names(BaseBR2015)

desenho = svydesign(id =~ escola,
                    
  strata =~ ESTRATOGEOREG,
  weights =~ as.numeric(PESO),
  data = BaseBR2015,
  nest = T)
desenho_RJ = subset(desenho, UFCENSO == 33 & TIPO_MUNIC == 1) 

```

```{r}
ekm = svykm(Surv(tempo,censura)~1,design = desenho_RJ )
b = plot(ekm,  xlab="Tempo (anos)",xlim = c(7,19), ylab="S(t) estimada")
Legenda = c("Kaplan-Meier ")
legend("bottomleft", Legenda)
```


### Estimação dos parametros e intervalo de confiança do paramêtro
```{r}
ajuste_exp = svysurvreg(Surv(tempo,censura)~1,design = desenho_RJ, dist='exponential')
ajuste_exp 


# Somente 2117 elementos? Não está fazendo para população ? 
# table(MUNICIPIO_CAP == 3304557) , amostra, 2119
# svytable(~factor(MUNICIPIO_CAP == 3304557),desenho_RJ), população, 71042.72


alfa_exp = exp(ajuste_exp$coefficients[1])
#alfa_exp, e ^ lambda 

varalfa_exp = ajuste_exp$var[1, 1]*(exp(ajuste_exp$coefficient[1]))^2 # Variância do parâmetro

IC = c(alfa_exp-qnorm(0.975)*sqrt(varalfa_exp),alfa_exp+qnorm(0.975)*sqrt(varalfa_exp)) # Intervalo de confiança de 95 para o parâmetro. 

#IC

```

### Estimação da função taxa de falha 
```{r}
lambda_exp = 1/alfa_exp
#lambda_exp

lambda_exp = function(t){1/alfa_exp*(t^0)} #Criando uma função no R para a taxa de falha
#plot(lambda_exp,ylab=expression(lambda(t)),xlab="t (em meses)",xlim=c(0,45))

```

### Estimando o percentil 100p%:
```{r}
perc_exp<-function(p){-alfa_exp*log(1-p)} #Criando uma função no R para o percentil
#perc_exp(p=0.05)#estimando o percentil 5%
#perc_exp(p=0.5)#estimando o percentil 50% ou mediana

#plot(perc_exp,ylab="tempo (em anos)",xlab="p")#plotando o percentil versus p

```

  ### Estimando a função de sobrevivência
```{r}
S_exp = function(t){exp(-t/alfa_exp)}#criando uma função no R para a sobrevivência
var_S_exp = function(t){varalfa_exp*((t/alfa_exp^2)*exp(-t/alfa_exp))^2} #criando uma função no R para a variância da função de sobrevivência

S_exp(t=14)#estimando a função de sobrevivência em 14 anos
c(S_exp(t=14)-qnorm(0.975)*sqrt(var_S_exp(t=1)),S_exp(t=1)+qnorm(0.975)*sqrt(var_S_exp(t=1)))#IC 95%

# A chance de um jovem não ter iniciando sua vida sexual até os 14 anos é de 75% com IC (0.75, 0.98)

a = plot(S_exp,ylab="S(t)",xlab="tempo (em anos)",xlim=c(0,100))
```

### Sobrepondo o estimador de kaplan meier e a estimação exponencial
```{r} 

```
