

```{r}
################################
# Carregando pacotes necessários.
################################
library(srvyr)
library("dplyr")
library("readxl")
library(survival)
library(survey)
library(flexsurv)
library(devtools)
BaseBR2015 = read.csv2(file = 'PENSE.csv',header=T, sep=";")
attach(BaseBR2015)
i = 1 
tempo = c()
censura = c()
while (i <= length(BaseBR2015$VB08002)){
  
  if (BaseBR2015$VB08002[i] == -1){
    
    tempo = append(tempo,BaseBR2015$VB01003[i])
    censura = append(censura, 0)
    i = i + 1
  }  
  
  
  else if (BaseBR2015$VB08002[i]>=9 && BaseBR2015$VB08002[i]<=18){
    
    tempo = append(tempo,BaseBR2015$VB08002[i])
    censura = append(censura, 1)
    i = i + 1
  }
    
  
  else if (BaseBR2015$VB08002[i] == 99 || BaseBR2015$VB08001[i] == 99){
    tempo = append(tempo, NA)
    censura = append(censura, NA) # o ERRO ESTÃ NO NA COMO STRING
    i = i + 1
    
  }
}
  
BaseBR2015 <- transform(BaseBR2015, tempo=tempo, censura=censura)
names(BaseBR2015)
desenho = svydesign(id =~ escola,
                    
  strata =~ ESTRATOGEOREG,
  weights =~ as.numeric(PESO),
  data = BaseBR2015,
  nest = T)
desenho_RJ = subset(desenho, UFCENSO == 33 & TIPO_MUNIC == 1) 
```

### exponencial 
```{r}
ajust1 = svysurvreg(Surv(tempo,censura)~1, design = desenho_RJ, dist='exponential')
ajust1

print('---------------------------------------------------------------------------------------')

alpha = exp(ajust1$coefficients[1])
alpha

```

### weibull 
```{r}
ajust2 = svysurvreg(Surv(tempo,censura)~1, design = desenho_RJ, dist='weibull')
ajust2

print('---------------------------------------------------------------------------------------')

alpha = exp(ajust2$coefficients[1])
beta = 1/ajust2$scale
cbind(beta,alpha)


```

### lognormal 
```{r}
ajust3 = svysurvreg(Surv(tempo,censura)~1,design = desenho_RJ, dist='lognormal')
ajust3

print('---------------------------------------------------------------------------------------')

```



```{r}
ekm = svykm(Surv(tempo,censura)~1,design = desenho_RJ )
summary(ekm)

time = ekm$time
st = ekm$surv

ste = exp(-time/ 50.73075) # Sobrevivencia exp

stw = exp(-(time/16.33128)^9.521658)  # Sobrevivencia weibul 


stln = pnorm((-log(time)+ 2.785874 )/0.1893781 ) # sobrevivencia lognormal

print('---------------------------------------------------------------------------------------')

cbind(time,st,ste,stw,stln)


```

### Lineariza a função de sobrevivencia, teste gráfico 2  
```{r}
par(mfrow=c(1,3))
plot(st,ste,pch=16,ylim=range(c(0.0,1)),xlim=range(c(0,1)),xlab="S(t):Kaplan-Meier",ylab="S(t):exponencial")
lines(c(0,1),c(0,1),type="l",lty=1)

plot(st,stw,pch=16,ylim=range(c(0.0,1)),xlim=range(c(0,1)),xlab="S(t):Kaplan-Meier",ylab="S(t):Weibull")
lines(c(0,1),c(0,1),type="l",lty=1)

plot(st,stln,pch=16,ylim=range(c(0.0,1)),xlim=range(c(0,1)),xlab="S(t):Kaplan-Meier",ylab="S(t):lognormal")
lines(c(0,1),c(0,1),type="l",lty=1)


```





### Teste gráfico 1, expo
```{r}

plot(ekm,conf.int=F,xlim = c(0,20), xlab="Tempo",ylab="S(t)")

lines(c(0,time),c(1,ste),lty=2)

legenda = c("Kaplan-Meier","exponencial")
legend("bottomleft", legenda ,lty=c(1,2),legenda, bty="n" ,cex=0.8)


```






### Teste gráfico 1, weibull 
```{r}

plot(ekm,conf.int=F,xlim = c(0,20), xlab="Tempo",ylab="S(t)")

lines(c(0,time),c(1,stw),lty=2)

legenda = c("Kaplan-Meier","Weibull")
legend("bottomleft", legenda ,lty=c(1,2),legenda, bty="n" ,cex=0.8)


```

Teste gráfico 1, lognormal
```{r}
plot(ekm,conf.int=F,xlim = c(0,20), xlab="Tempo",ylab="S(t)")

lines(c(0,time),c(1,stln),lty=2)

legenda = c("Kaplan-Meier","log-normal")
legend("bottomleft", legenda ,lty=c(1,2),legenda, bty="n" ,cex=0.8)
```

```{r}

```

```{r}

```