---
title: "R Notebook"
output: html_notebook
---



```{r}
library(srvyr)
library("dplyr")
library("readxl")
library(survival)
library(survey)
library(flexsurv)
library(devtools)

BaseBR2015 = read.csv2(file = 'PENSE.csv',header=T, sep=";")
attach(BaseBR2015) 

escolaridadeMae = c()

for (x in 1:length(BaseBR2015$VB01008A)){
  
  #Nova regra, Não estudou (1)
  
  if (BaseBR2015$VB01008A[x] == 1 || BaseBR2015$VB01008A[x] == 2){
    escolaridadeMae = append(escolaridadeMae,1)
  }
  
  #Nova regra, Ensino Fundamental (2)
  else if (BaseBR2015$VB01008A[x] == 3 || BaseBR2015$VB01008A[x] == 4){
    escolaridadeMae = append(escolaridadeMae,2)
  }
  
  #Nova regra, ensino médio (3)
  else if (BaseBR2015$VB01008A[x] == 5 || BaseBR2015$VB01008A[x] == 6){
    escolaridadeMae = append(escolaridadeMae,3)
  } 
  
  #Nova regra, ensino superior(4)
  else if (BaseBR2015$VB01008A[x] == 7){
    escolaridadeMae = append(escolaridadeMae,4)
  }
  
  #Nova regra, não sei (5)
  else if (BaseBR2015$VB01008A[x] == 8){
    escolaridadeMae = append(escolaridadeMae,5)
  }
  
  # Não informado (99)
  else if (BaseBR2015$VB01008A[x] == 99){
    escolaridadeMae = append(escolaridadeMae,99)
  }
}

# Conferido com table(BaseBR2015$VB01008A) e  table(escolaridadeMae) 

# Criando a variavel tempo e censura


i = 1 
tempo = c()
censura = c()
while (i <= length(BaseBR2015$VB08002)){
  
  if (BaseBR2015$VB08002[i] == -1){
    
    tempo = append(tempo,BaseBR2015$VB01003[i])
    censura = append(censura, 0)
    i = i + 1
  }  
  
  
  else if (BaseBR2015$VB08002[i]>=9 && BaseBR2015$VB08002[i]<=18){
    
    tempo = append(tempo,BaseBR2015$VB08002[i])
    censura = append(censura, 1)
    i = i + 1
  }
    
  
  else if (BaseBR2015$VB08002[i] == 99 || BaseBR2015$VB08001[i] == 99){
    tempo = append(tempo, 0) # Se deixar NA o logrank da erro
    censura = append(censura, 0) # o ERRO ESTÃ NO NA COMO STRING
    i = i + 1
    
  }
}

BaseBR2015 = transform(BaseBR2015, tempo=tempo, censura=censura, escolaridadeMae = escolaridadeMae)
names(BaseBR2015)


desenho = svydesign(id =~ escola,
                    
  strata =~ ESTRATOGEOREG,
  weights =~ as.numeric(PESO),
  data = BaseBR2015,
  nest = T)

desenhobr = subset(desenho, PAIS == 76) 
desenhoRJ = subset(desenho, UFCENSO == 33 & TIPO_MUNIC == 1)
```

# Distribuição de Frequências
```{r}

svytable(~factor(escolaridadeMae),desenhoRJ)

#1 -> Não estudou
#2 -> Ensino fundamental
#3 -> Ensino Médio
#4 -> Ensino Superior
#5 -> Não sei
#99 -> Não informado

escolaridade = c("Não estudou", "Ensino Fundamental", "Ensino Médio", "Ensino Superior","Não sei", "Não informado")

valores = c(9647.403, 9267.901, 22377.068, 13864.420, 15720.122, 165.805)

porce = 100/sum(valores)

porcentagem = valores*porce

tabela = data.frame( Escolaridade_Da_Mãe = escolaridade, Valores = valores, Porcentagem = porcentagem)

tabela
```

# Curva de Kaplan meier
```{r}
ekm.escolaridade = svykm(Surv(tempo,censura)~escolaridadeMae,design=desenhoRJ)

plot(ekm.escolaridade, ylab = "S(t) estimada",xlab = "Tempo (idade)"
     ,pars=list(lty=c(1,2,1,2,1,1),col=c("Green","black","red","pink","black","transparent")))

Legenda<-c("Não estudou", "Ensino fundamental", "Ensino Médio","Ensino Superior","Não sei","Não informado")

legend("bottomleft", Legenda,lwd=c(1,1),cex=1,inset=0.00,col=c("Green","black","red","pink","black","transparent"),bty="n", lty = c(1,2,1,2,1,1))

# retirei o não informado
```

# Log rank, P-VAlor

```{r}
ekm.escolaridade = svykm(Surv(tempo,censura)~escolaridadeMae,design=desenhoRJ)
svylogrank(Surv(tempo,censura)~escolaridadeMae,design=desenhoRJ)
```

# Tempo Mediano

```{r}
ekm.escolaridade = svykm(Surv(tempo,censura)~escolaridadeMae,design=desenhoRJ)
ekm.escolaridade

# Não estudou, mediana 16
# Ensino fundamental, mediana inf ?
# Ensino médio, mediana 18  
# Ensino superio, mediana inf 
# Não sei, mediana inf 
# Não informado, mediana 16
```