---
title: "R Notebook"
output: html_notebook
---


# Categorizando a variavel cor
```{r}

library(srvyr)
library("dplyr")
library("readxl")
library(survival)
library(survey)
library(flexsurv)
library(devtools)

BaseBR2015 = read.csv2(file = 'PENSE.csv',header=T, sep=";")
attach(BaseBR2015)


raca = c()
for (x in 1:length(BaseBR2015$VB01002)){
  
  # Nova regra, 1 branca
  if (BaseBR2015$VB01002[x] == 1){
    raca = append(raca,1)
    
  }
  
  # Nova regra, 2 Negra
  else if (BaseBR2015$VB01002[x] == 2 ){
    raca = append(raca,2)
  
  }
  
  # Nova regra, 2 negra
  else if(BaseBR2015$VB01002[x] == 4){
    raca = append(raca,2)
  }

  # Nova regra, 3 outras
  
  else if (BaseBR2015$VB01002[x] == 3) {
    raca = append(raca,3)
    
  }
  
  # Nova regra, 3 outras
  else if(BaseBR2015$VB01002[x] == 5){
    raca = append(raca,3)
  }
  
  #Nova regra, 99 Não informado
  else {
    raca = append(raca, 99)
   
  } 
}



# Criando a variavel tempo e censura


i = 1 
tempo = c()
censura = c()
while (i <= length(BaseBR2015$VB08002)){
  
  if (BaseBR2015$VB08002[i] == -1){
    
    tempo = append(tempo,BaseBR2015$VB01003[i])
    censura = append(censura, 0)
    i = i + 1
  }  
  
  
  else if (BaseBR2015$VB08002[i]>=9 && BaseBR2015$VB08002[i]<=18){
    
    tempo = append(tempo,BaseBR2015$VB08002[i])
    censura = append(censura, 1)
    i = i + 1
  }
    
  
  else if (BaseBR2015$VB08002[i] == 99 || BaseBR2015$VB08001[i] == 99){
    tempo = append(tempo, 0) # Se deixar NA o logrank da erro
    censura = append(censura, 0) # o ERRO ESTÃ NO NA COMO STRING
    i = i + 1
    
  }
}

BaseBR2015 = transform(BaseBR2015, tempo=tempo, censura=censura, raca = raca)
names(BaseBR2015)



# Aplicando o desenho da amostra


desenho = svydesign(id =~ escola,
                    
  strata =~ ESTRATOGEOREG,
  weights =~ as.numeric(PESO),
  data = BaseBR2015,
  nest = T)

desenhobr = subset(desenho, PAIS == 76) 
desenhoRJ = subset(desenho, UFCENSO == 33 & TIPO_MUNIC == 1)
```



# Distribuição de Frequências
```{r}
svytable(~factor(raca),desenhoRJ)

#Outras : amarelo + indígna
raca = c("Branca", "Negra", "Outras", "Não informado")

 valores = c(30507.77279, 35056.92370, 5442.74393, 35.27889)

porce = 100/sum(valores)

porcentagem = valores*porce

tabela = data.frame( Raça = raca, Valores = valores, Porcentagem = porcentagem)

tabela
```

# Curva de Kaplan meier
```{r}


ekm.raca = svykm(Surv(tempo,censura)~raca,design=desenhoRJ, )

plot(ekm.raca, ylab = "S(t) estimada",xlab = "Tempo (idade)"
     ,pars=list(lty=c(1,2,1,2),col=c("green","black","red", "transparent")))

Legenda<-c("Verde", "Preta", "Outras ",  "Não informada")

legend("bottomleft", Legenda,lwd=c(1,1),cex=1,inset=0.00,col=c("green","black","red", "transparent"),bty="n", lty = c(1,2,1,2))

```

#lOGRANK, P-VALOr
```{r}
ekm.raca = svykm(Surv(tempo,censura)~raca,design=desenhoRJ)
svylogrank(Surv(tempo,censura)~raca,design=desenhoRJ)

```

# Tempo mediano

```{r}
ekm.raca = svykm(Surv(tempo,censura)~raca,design=desenhoRJ)
ekm.raca

# 1 branca, mediana 18 
# 2 preta, mediana 17 
# 3 outras, mediana inf ???


```

